### ISSUE TITLE
No se envían los correos electrónicos: "EDV. La carpeta no existe o se está intentando generar un archivo que ya está abierto"

### ISSUE THREAD

**Issue by israelpelayo** [davidbuenov/CombinarCorrespondencia#5]
Hola. Gracias por tu proyecto, está genial. Desafortunadamente, no he podido utilizar el envío de correos electrónicos. Utilizo un archivo de Excel que contiene mi base de datos con múltiples campos en formato horizontal y vertical, y los campos que requiero los inserto por correspondencia de Word, como lo has mostrado en tus múltiples videos. El problema es que la aplicación comienza a procesar pero se detiene en el primer archivo. Sólo crea el primer archivo y luego salta el error "EDV. La carpeta no existe o se está intentando generar un archivo que ya está abierto. Cierra el archivo: d:\ (DIRECCIÓN+ NOMBRE DE ARCHIVO)" y, finalmente, no envía y no procesa el resto. Intenté cientos (literal) de formas, cambiando correos, reiniciando el equipo, cambiando archivo de word, cambiando mi base de datos, reemplazando los datos de tus archivos de ejemplo con los míos, cambio ubicaciones, etc. Curiosamente, si corro tus ejemplos en mi equipo sí se generan los archivos y se envían por correo correctamente, pero con mis propios archivos fue inútil el esfuerzo (llevo al menos unas 6 horas intentándolo). Si sólo intento guardar los archivos en mi equipo sí se guardan. El problema radica en el envío de los correos. 

Tengo Windows 11, office 365, una laptop OMEN DC003LA. 

Te agradezco por tu apoyo y por tu excelente proyecto. 

PD.
Este mismo error lo miré con alguien que comentó en tus videos de YouTube

**Comment by davidbuenov** [comment]
Hola Israel,

Eso suele pasar porque se ha abierto un archivo .pdf y al intentar generar de nuevo la aplicación no puede. También te puede pasar porque hayas hecho una primera generación y el documento combinado haya eliminado las etiquetas, con lo que deberías volver a la versión inicial.  Ayer subí una nueva versión con nuevas funcionalidades, y en cuanto pueda voy a hacer todos los videos actualizados con esta versión que espero que te funcione bien.

Gracias por tu apoyo y feliz navidad

**Comment by israelpelayo** [comment]
David, te agradezco por todo tu apoyo. Este tipo de funciones que has logrado no deberían pasar desapercibidas, ayudan demasiado. Es fantástica tu aplicación. Revisaré el nuevo material que mencionas, esperando pueda utilizarlo. Feliz año 2022 y mis mejores deseos para ti y tu familia.
